### ISSUE TITLE
Uvoz in grafi

### ISSUE THREAD

**Issue by jaanos** [StekovicZ12/APPR-2014-15#1]
Pri uvozu iz CSV lahko prvi stolpec vzameš za imena vrstic, kar dosežeš tako, da podaš parameter `row.names = 1` pri branju iz CSV. Podatke o izobrazbi po regijah uvoziš tudi iz XML, tako da lahko uvoz teh podatkov iz CSV odstraniš.

Risanje grafov imaš narejeno, a ga nikjer ne kličeš. Najbolje bo, če to narediš kar v glavnem programu.

**Comment by jaanos** [comment]
Zgornje si uredila, ampak sedaj poskušaš risati grafa iz spremenljivke `izobrazba.poregijah`, ki je več nimaš, oziroma si jo nadomestila s spremenljivko `poRegijah`. Ta ima druga imena stolpcev, imena regij pa so v imenih vrstic (te dobiš z `rownames`).

V poročilu imaš tudi imena datotek in spremenljivk - lepo bi bilo, če se ločijo od ostalega besedila, kar lahko dosežeš z ukazom `\verb`, npr.

``` LaTeX
\verb|xml.r|
```

Tako se tudi znebiš problemov z morebitnimi posebnimi znaki. Znak `|` takoj za `\verb` služi kot oznaka za konec niza - po potrebi ga lahko zamenjaš (npr. `\verb+|+` ti izpiše ravno ta znak). Druga možnost, primerna tudi za spletne naslove, je uporaba paketa `url` in ukaza `\url`.

**Comment by StekovicZ12** [comment]
Sem uredila.
